import { DevtoolsProvider } from "@providers/devtools";
import { Refine } from "@refinedev/core";
import { RefineKbar, RefineKbarProvider } from "@refinedev/kbar";
import routerProvider from "@refinedev/nextjs-router";
import { Metadata } from "next";
import React, { Suspense } from "react";
import { dataProvider } from "@providers/data-provider";
import { ApolloWrapper } from "@providers/apollo-provider/ApolloWrapper";
import { MantineProvider } from "@mantine/core";
import Layout from "@components/customLayout/Layout";

import "@mantine/core/styles.css";
import "@styles/global.css";

export const metadata: Metadata = {
  title: "ebixi task",
  description: "Generated by create refine app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Suspense>
          <RefineKbarProvider>
            <DevtoolsProvider>
              <ApolloWrapper>
                <MantineProvider>
                  <Refine
                    routerProvider={routerProvider}
                    dataProvider={dataProvider}
                    options={{
                      syncWithLocation: true,
                      warnWhenUnsavedChanges: true,
                      useNewQueryKeys: true,
                      projectId: "SY0ll3-FYukqS-vdwvqq",
                    }}
                  >
                    <Layout>{children}</Layout>
                    <RefineKbar />
                  </Refine>
                </MantineProvider>
              </ApolloWrapper>
            </DevtoolsProvider>
          </RefineKbarProvider>
        </Suspense>
      </body>
    </html>
  );
}
